[project]
name = "art-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agents>=1.4.0",
    "asyncio>=3.4.3",
    "mcp>=1.11.0",
    "openai>=1.74.0",
    "python-dotenv>=1.1.1",
]
